package OperacionesApp;


/**
* OperacionesApp/OperacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperacionesApp.idl
* Sunday, November 15, 2020 3:29:06 PM CST
*/

public interface OperacionesOperations 
{
  String saludar ();
  String obtenerInfo ();
  void shutdown ();
} // interface OperacionesOperations
