package OperacionesApp;


/**
* OperacionesApp/Operaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperacionesApp.idl
* Sunday, November 15, 2020 3:29:06 PM CST
*/

public interface Operaciones extends OperacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operaciones
